-- CREATE TABLE IF NOT EXISTS filter (
--                         "id" BIGINT AUTO_INCREMENT PRIMARY KEY,
--                         "name" VARCHAR(255) NOT NULL UNIQUE,
--                         "createdAt" TIMESTAMP NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS criteria (
--                           "id" BIGINT AUTO_INCREMENT PRIMARY KEY,
--                           "type" VARCHAR(50) NOT NULL,
--                           "criteria_condition" VARCHAR(255) NOT NULL,
--                           "value" VARCHAR(255),
--                           "filter_id" BIGINT,
--                           FOREIGN KEY ("filter_id") REFERENCES "filter" ("id") ON DELETE CASCADE
-- );